import turtle


tela = turtle.Screen()
tela.bgcolor("green")

desenhista = turtle.Turtle()
desenhista.fillcolor("yellow")
desenhista.begin_fill()
desenhista.forward(200)
desenhista.left(90)
desenhista.forward(200)
desenhista.left(90)
desenhista.forward(200)
desenhista.left(90)
desenhista.forward(200)
desenhista.left(90)
desenhista.end_fill()
desenhista.penup()
desenhista.goto(0,200)
desenhista.pendown()
desenhista.fillcolor("red")
desenhista.begin_fill()
desenhista.left(45)
desenhista.forward(140*(2**1/2))
desenhista.right(90)
desenhista.goto(200, 200)
desenhista.end_fill()
desenhista.penup()
desenhista.goto(70,0)
desenhista.pendown
desenhista.left(135)
desenhista.fillcolor("brown")
desenhista.begin_fill()
desenhista.forward(100)
desenhista.right(90)
desenhista.forward(40)
desenhista.right(90)
desenhista.forward(100)
desenhista.right(90)
desenhista.forward(40)
desenhista.end_fill()

tela.exitonclick()